Use an extra step to get the ruby-version in docker image
   You can't see the "inputs" contexts in the "image:" setting for a step.
   https://stackoverflow.com/questions/59191913/how-do-i-get-the-output-of-a-specific-step-in-github-actions
   So we add in yet another step to get the variable which can then be used.
   There is probably a line somewhere in githubs docs that explain this but I'm
   not sure I can see it.

   My hope is this will fix the following error:

    Error:
      university-of-york/faculty-dev-actions/v1/ruby-command/action.yaml
      (Line: 14, Col: 10):
      Unrecognized named-value: 'inputs'. Located at position 1
      within expression: inputs.ruby-version
    Error: Fail to load university-of-york/faculty-dev-actions/v1/ruby-command/action.yaml